server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service
              uri: lb://PATIENT-SERVICE
              predicates:
                - Path=/api/v1/patients/**, /api/v1/patients
            - id: doctor-service
              uri: lb://DOCTOR-SERVICE
              predicates:
                - Path=/api/v1/doctors/**, /api/v1/doctors
            - id: appointment-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                - Path=/api/v1/appointments/**, /api/v1/appointments, /api/v1/appointment/**, /api/v1/appointment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.example.medicalgateway: DEBUG

