server:
  port: 8081

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    refresh:
      enable: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: postgres
    password: '{cipher}27ccf300dc1586002a6846097f9cd92cb8df5608ae5c7095c66ad59ddca7323bce0db42434e7a76705baa766f24c2fad'
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

app:
  welcome: "Hệ thống y tế Rikkei - Cấu hình đã cập nhật thành công qua Actuator /refresh"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [cid:%X{correlationId:-N/A}] %logger{36} - %msg%n"
  level:
    com.example.patientservice: DEBUG