server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: ${POSTGRES_USER:rikkei}
    password: '{cipher}ae1bdd9c598a6eafcb2f0b9f13476561af83802f1e451d8d9b86de56509d616e'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [cid:%X{correlationId:-N/A}] %logger{36} - %msg%n"
  level:
    com.example.patientservice: DEBUG