server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: postgres
    password: '{cipher}9ba4818d9cc34fe0ffa82ecb46615aeccf1c641f14b308365c71ee1829505db3'
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

app:
  welcome: "Hệ thống y tế Rikkei - Cập nhật tự động qua /refresh"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [cid:%X{correlationId:-N/A}] %logger{36} - %msg%n"
  level:
    com.example.patientservice: DEBUG