spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: ${POSTGRES_USER:rikkei}
    password: ${POSTGRES_PASSWORD:rikkei}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [cid:%X{correlationId:-N/A}] %logger{36} - %msg%n"
  level:
    com.example.patientservice: DEBUG

app:
  welcome: "Chào mừng tới BV RikkeiEducation"